apiVersion: apps/v1
kind: Deployment
metadata:
  name: discounts-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: restaurant_discounts
  template:
    metadata:
      labels:
        app: restaurant_discounts
    spec:
      containers:
        - name: restaurant_discounts
          image: ugougo05/discounts:latest
          ports:
            - containerPort: 3001
          env:
            - name: SECRET
              value: "${{ secrets.SECRET }}"
            - name: MONGODB_URI
              value: "${{ secrets.MONGODB_URI }}"
            - name: CLOUD_NAME
              value: "${{ secrets.CLOUD_NAME }}"
            - name: CLOUD_API_KEY
              value: "${{ secrets.CLOUD_API_KEY }}"
            - name: CLOUD_API_SECRET
              value: "${{ secrets.CLOUD_API_SECRET }}"
---
apiVersion: v1
kind: Service
metadata:
  name: discounts-service
spec:
  selector:
    app: restaurant_discounts
  ports:
    - port: 3002
      targetPort: 3002
