apiVersion: apps/v1
kind: Deployment
metadata:
  name: client-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: restaurant_client
  template:
    metadata:
      labels:
        app: restaurant_client
    spec:
      containers:
        - name: restaurant_client
          image: ugougo05/client:latest
          ports:
            - containerPort: 3000
          env:
            - name: SECRET
              value: "${{ secrets.SECRET }}"
            - name: MONGODB_URI
              value: "${{ secrets.MONGODB_URI }}"
            - name: CLOUD_NAME
              value: "${{ secrets.CLOUD_NAME }}"
            - name: CLOUD_API_KEY
              value: "${{ secrets.CLOUD_API_KEY }}"
            - name: CLOUD_API_SECRET
              value: "${{ secrets.CLOUD_API_SECRET }}"
---
apiVersion: v1
kind: Service
metadata:
  name: client-service
spec:
  selector:
    app: restaurant_client
  ports:
    - port: 3000
      targetPort: 3000
