---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: items-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: restaurant-items
  template:
    metadata:
      labels:
        app: restaurant-items
    spec:
      containers:
      - name: restaurant-items
        image: ugougo05/items:latest
        ports:
        - containerPort: 3003
        env:
        # Database Configuration
        - name: MONGODB_URI_ITEMS
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: MONGODB_URI_ITEMS
        - name: DB_HOST
          value: "mongodb-service"
        - name: DB_PORT
          value: "27017"
        
        # Application Secrets
        - name: SECRET
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: SECRET
        
        # Cloudinary Configuration
        - name: CLOUD_NAME
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: CLOUD_NAME
        - name: CLOUD_API_KEY
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: CLOUD_API_KEY
        - name: CLOUD_API_SECRET
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: CLOUD_API_SECRET

         
---
apiVersion: v1
kind: Service
metadata:
  name: items-service
spec:
  selector:
    app: restaurant-items
  ports:
    - port: 3003
      targetPort: 3003