name: Rollout and Cleanup Deployments

on:
  workflow_run:
    workflows: ["CI/CD Pipeline"]  # <-- Replace with your actual deployment workflow name
    types:
      - completed

jobs:
  restart-and-clean:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Set up Kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: 'latest'

      - name: Authenticate to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Get AKS Credentials
        run: |
          az aks get-credentials \
            --resource-group bud-restauranty-rg \
            --name bud-restauranty-cluster \
            --overwrite-existing

      - name: Rollout Restart Deployments
        run: |
          deployments=(
            "auth-deployment"
            "discounts-deployment" 
            "items-deployment"
            "client-deployment"
          )

          for deployment in "${deployments[@]}"; do
            echo "Restarting $deployment..."
            kubectl rollout restart deployment/$deployment

            # Wait with timeout
            if ! kubectl rollout status deployment/$deployment --timeout=90s; then
              echo "::warning::Rollout for $deployment timed out"
              kubectl delete pods --field-selector=status.phase!=Running --force --grace-period=0
            fi
          done

      - name: Delete Completed Pods
        run: |
          completed_pods=$(kubectl get pods --field-selector=status.phase=Succeeded -o name)
          if [ -n "$completed_pods" ]; then
            echo "Deleting completed pods..."
            echo "$completed_pods" | xargs kubectl delete
          else
            echo "No completed pods to delete."
          fi